# Generated by Django 4.0.4 on 2022-05-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='user',
            new_name='users',
        ),
    ]
