# Generated by Django 4.0.4 on 2022-05-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_bookings_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start'], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.DateTimeField(unique=True, verbose_name='Inicio'),
        ),
    ]
