# Generated by Django 4.0.4 on 2022-05-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_created_at_booking_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sabado'), ('7', 'Domingo')], max_length=10, verbose_name='Dia de la semana')),
                ('hour', models.TimeField(verbose_name='Hora')),
            ],
            options={
                'verbose_name': 'Hora',
                'verbose_name_plural': 'Horas',
                'unique_together': {('day_of_week', 'hour')},
            },
        ),
    ]
