# Generated by Django 4.0.4 on 2022-05-29 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0008_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
    ]
